{% set name = "entsoe-py" %}
{% set version = "0.3.4" %}
{% set sha256 = "6f00633d7333d4db355c5da90fd9c370cec0237b11c1e3945fac606b8b5fc29b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - beautifulsoup4
    - pandas
    - python >=3.6
    - pytz
    - requests

test:
  imports:
    - entsoe

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: Python client for the ENTSO-E API (european network of transmission system operators for electricity)
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
