{% set name = "entsoe-py" %}
{% set version = "0.6.11" %}
{% set sha256 = "6f317b34fee4c656e4eb4b3c73c0593f3ef4bd3866564956e46304ae411906e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - beautifulsoup4
    - pandas
    - python >={{ python_min }}
    - pytz
    - requests
    - geojson-rewind
    - python-dateutil
    - geopandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - entsoe

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: Python client for the ENTSO-E API (european network of transmission system operators for electricity)
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
