{% set name = "entsoe-py" %}
{% set version = "0.2.12" %}
{% set sha256 = "da023b8d8b39dc3229b609f2a074a45d1c4244b9a96ee3480439dd18eb3a8445" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - beautifulsoup4
    - pandas
    - python
    - pytz
    - requests

test:
  imports:
    - entsoe

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: Python client for the ENTSO-E API (european network of transmission system operators for electricity)
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
