{% set name = "entsoe-py" %}
{% set version = "0.6.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/entsoe_py-{{ version }}.tar.gz
  sha256: 67fb865d5af94b0b841f75ed30accde9ed82923a6b0160ce9c604ae50abb4c0d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - pytz
    - beautifulsoup4 >=4.11.1
    - pandas >=2.2.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - entsoe
  commands:
    - pip check

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: Python client for the ENTSO-E API (european network of transmission system operators for electricity)
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
    - xylar
