{% set name = "entsoe-py" %}
{% set version = "0.2.11" %}
{% set sha256 = "b31e8affb95f0c7ce9bcfa1b2110ebc0da9d9f6dd7019f8984d4eeb930052fc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv "

requirements:
  host: 
    - python
    - pip
  run:
    - beautifulsoup4
    - pandas
    - python
    - pytz
    - requests

test:
  imports:
    - entsoe

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: 'Python client for the ENTSO-E API (european network of transmission system operators for electricity)'
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
